### ISSUE TITLE
Proper syntax

### ISSUE THREAD

**Issue by zzxxddffdle** [sfuhrm/radiorecorder#27]
I am trying to record http://stream.radioparadise.com/aac-320. I have been unable to figure out the syntax to start the stream. Windows 10.  Directory I wish to record to: D:\RadioRecord. Would you mind helping me with a proper command to record this? Thanks.

**Comment by filimonic** [comment]
"C:\Program Files\radiorecorder\radiorecorder.exe"   http://stream.radioparadise.com/aac-320   -directory   "D:\RadioRecord"  -use-songnames

**Comment by sfuhrm** [comment]
The example of @filimonic  seems to do the trick. Thanks, @filimonic !
