### ISSUE TITLE
Doesn't record on Windows

### ISSUE THREAD

**Issue by HumLab-AAU** [sfuhrm/radiorecorder#3]
Hi, 

This seems like great tool, but I can't get it to work on Windows 11. I installed the msi without problems and I can play from the commands line, e.g.:

```
C:\Program Files\radiorecorder>radiorecorder.exe -play 96301ea7-0601-11e8-ae97-52543be04c81
INFO: Starting radio: Radio(name=181.FM - Christmas Classics, url=http://www.181.fm/stream/pls/181-xtraditional.pls, uuid=96301ea7-0601-11e8-ae97-52543be04c81, favIconUrl=null, codec=MP3, bitrate=0, tags=[])
INFO: Track: 21.42: 181.FM Christmas Classics ->
INFO: Track: 21.42: 181.FM Christmas Classics -> Bing Crosby & The Andrews Sisters - Twelve Days Of Christmas

```
But recording fails: 

```
C:\Program Files\radiorecorder>radiorecorder.exe -S -r -d . 96301ea7-0601-11e8-ae97-52543be04c81
INFO: Starting radio: Radio(name=181.FM - Christmas Classics, url=http://www.181.fm/stream/pls/181-xtraditional.pls, uuid=96301ea7-0601-11e8-ae97-52543be04c81, favIconUrl=null, codec=MP3, bitrate=0, tags=[])
WARN: File number finding problem
java.nio.file.NoSuchFileException: .\181.FM+-+Christmas+ClassicsINFO: Dropped 8192 bytes, no file name yet
INFO: Dropped 5308 bytes, no file name yet
INFO: Dropped 2500 bytes, no file name yet
INFO: Track: 21.31: 181.FM Christmas Classics -> Glenn Miller - Sleigh Ride
INFO: Deleting partly file .\181.FM+-+Christmas+Classics\001.Glenn Miller - Sleigh Ride .mp3
```

Any help is appreciated!

**Comment by snibles** [comment]
I'm having the exact same issue.
I installed on a PC running Windows 11 and this erros pop when I select the option to record something.
Maybe a OS specific error?

I'll try later on Mac OS and Linux.

**Comment by sfuhrm** [comment]
Hi, thanks for the issue. It looks like the app opens the stream and wants to download, but opening the output file fails.

Can you check with a different output directory than "."? 
Another possibiliy is that there are characters in the generated filenames that Windows doesn't like.

**Comment by sfuhrm** [comment]
You've changed the current working directory to be "C:\Program Files\radiorecorder" to have the radiorecorder.exe in your search path. You have set the output directory to be ".".

Windows does not allow a normal user to write to program directories. But you can write to your own directories.

The error message around
```
WARN: File number finding problem
java.nio.file.NoSuchFileException: .\181.FM+-+Christmas+ClassicsINFO: Dropped 8192 bytes, no file name yet
```

is not very helpful to understand the problem. 
Because of that I'm adding a check that checks for writability of the target directory and outputs a custom error message (see cb481c3b164a6de5b016f3c03dbb1aa4ac1034a5).

Will be included in next release > 1.5.8.

**Comment by sfuhrm** [comment]
See release 1.5.9

**Comment by snibles** [comment]
> See release 1.5.9

@sfuhrm 
Thanks!
I just writing back to confirm that this is working now on version 1.5.9

This is such a great software. Thank you!
