### ISSUE TITLE
I cannot open the app on Mac

### ISSUE THREAD

**Issue by Aelli69** [sfuhrm/radiorecorder#36]
Hi, unfortunately I cannot open the App on my Mac. After I open the App it immediately closes without any error message. I tried both png install and dmg install.

**Comment by sfuhrm** [comment]
It's a terminal application. Is it possible to execute it in a shell terminal window?

**Comment by Aelli69** [comment]
No, doesn't work. I deleted all possible quarantine files with this common 'xattr -d com.apple.quarantine /Applications/radiorecorder.app'and startet the app with bypassed security checks. But nothing worked.
The Icon flashes briefly in the Dock and that's it.
Im running a M1 Mac mini with 14.1.1 Sonoma

**Comment by sfuhrm** [comment]
As I said, you should not press the icon, but execute it in a terminal window.
Even if there is an icon, it won't work because the application is designed to be a terminal application.

**Comment by sfuhrm** [comment]
Can not reproduce, unclear error. Possibly wrong expectation of usage.
