### ISSUE TITLE
When using -use-songnames, it's a good idea to wait for next song at start, skipping recording current song from the middle. 

### ISSUE THREAD

**Issue by filimonic** [sfuhrm/radiorecorder#37]
When using `-use-songnames`, it's a good idea to wait for next song at start, skipping recording current song from the middle.
Maybe add `-skip-first-incomplete-song`

**Comment by sfuhrm** [comment]
Implementation finished

**Comment by sfuhrm** [comment]
Implemented in 1.8.2
