### ISSUE TITLE
Issue with international characters

### ISSUE THREAD

**Issue by snibles** [sfuhrm/radiorecorder#5]
Hi

I have a problem that the app is not recognizing international (accentuation) characters.
Is this something configurable in the application? Or this is coming from the stream?

Here is one example of a output from a station broadcasting in portuguese. The radio station is from Brazil.
I highlighted in bold the errors in the names....

C:\Program Files\radiorecorder>radiorecorder.exe -play 2ccd58d8-6924-49cb-8bce-ba10263f7bbb
INFO: Starting radio: Radio(name=Jovem Pan Pop Brasil, url=http://6d9a.webradio.upx.net.br:9046/stream?1597501793407, uuid=2ccd58d8-6924-49cb-8bce-ba10263f7bbb, favIconUrl=null, codec=MP3, bitrate=0, tags=[])
INFO: Track: 3:54 PM: Stream Name -> **Clß**udio Zoli - Noite do Prazer [4Ne]
INFO: Track: 3:56 PM: Stream Name -> **Cß**ssia Eller - Reli**cß**rio (Ao Vivo) [4MM]
INFO: Track: 3:59 PM: Stream Name -> **Cß**ssia Eller - Gatas Extraordin**ß**rias [4MH]
INFO: Track: 4:03 PM: Stream Name -> Legi**πo** Urbana - Ainda **Θ** Cedo [4Og]

Any idea?

**Comment by sfuhrm** [comment]
Hi, thanks for the issue! 

I just had an interesting result on Linux:

```
$ radiorecorder -p http://6d9a.webradio.upx.net.br:9046/stream?1597501793407
INFO: Starting radio: Radio(name=User-Suppplied URL, url=http://6d9a.webradio.upx.net.br:9046/stream?1597501793407, uuid=null, favIconUrl=null, codec=null, bitrate=0, tags=[])
INFO: Track: 19:01: Stream Name -> Lulu Santos - Um Certo Alguém [4OM]
...
INFO: Track: 19:05: Stream Name -> Tribalistas - Carnávalia [4Q7]
...
```
So on the Linux console it looks like the tracks are correct.
Can you try writing files to disk? Are the names then correct?

We can check this way whether it is an issue of the console charset setting.

**Comment by sfuhrm** [comment]
Can not reproduce. To me it looks like this is depending on your system setup since I don't have this issue on my system.

**Comment by snibles** [comment]
> Can not reproduce. To me it looks like this is depending on your system setup since I don't have this issue on my system.

You're correct!
I tried on my Linux system and it works correctly.
I reinstalled on my Windows system, and it works correctly now.

Thanks!
