### ISSUE TITLE
Feature Request: Abort after X minutes

### ISSUE THREAD

**Issue by snibles** [sfuhrm/radiorecorder#6]
Hi!

I would be awesome if it was possible to have a feature like -abort-after KB, but for time.
Something like -abort-after-minutes where we can set the amount, like 60 minutes, and after this, the recording is automatically stoped. 
This would be an immense help for people like me is trying to record a schedule show, everyday, that has a duration of 60 minutes.

Thanks!

**Comment by autonompost** [comment]
yes, that really would be great. Of course, you can write a wrapper script that terminates the recording after a certain time.

**Comment by sfuhrm** [comment]
`-abort-after-duration` option is now in the source

**Comment by sfuhrm** [comment]
https://github.com/sfuhrm/radiorecorder/releases/tag/v1.7.0
