### ISSUE TITLE
armhf release

### ISSUE THREAD

**Issue by furumc** [sfuhrm/radiorecorder#7]
Could you please compile it for armhf(banana pi, 32bit, ARMv7 Processor rev 3 (v7l), Mediatek Cortex-A7)?
I used to use streamripper, but from this year on my favourite radio station can't be ripped anymore through this way!
I should test your application!
Thank you in advance!

**Comment by sfuhrm** [comment]
There's no real need for a compile here. You can try it by installing Java JRE 8 or later and then download i.e. radiorecorder-1.5.8-bin.tar.bz2
The platform-specific packages are just a bundle of Java JRE + radioracorder application.

May be you can give the tar.bz2 a try? Feedback is welcome!

Providing packages for less-popular platforms will require some changes to the process. I don't yet want to do that :).
